name: flutter_tagging_demo
description: A demo application of multi-tag picker.
publish_to: none
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  multi_tag_picker:
    path: ../
  flutter_syntax_view: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
