name: multi_tag_picker
description: Flutter package for adding and choosing tags.
version: 1.0.0
repository: https://github.com/nlfiedler/multi_tag_picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: 1.17.0
  flutter_lints: ^2.0.1
  flutter_typeahead: ^4.0.0
  meta: 1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
